# Generated by Django 3.2.3 on 2021-05-28 09:11

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp8266',
            name='mac',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', blank=True, min_length=7, null=True, prefix=''),
        ),
    ]
