# Generated by Django 3.2.3 on 2021-05-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_esp8266_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp8266',
            name='mac_unhash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
