# Generated by Django 3.2.4 on 2022-04-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_esp8266_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esp8266',
            old_name='username',
            new_name='user',
        ),
    ]
