# Generated by Django 3.2.4 on 2022-07-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('index', '0008_auto_20220624_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applience',
            name='esp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliences', to='index.esp8266'),
        ),
        migrations.AlterField(
            model_name='changetime',
            name='Appliences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='index.applience'),
        ),
        migrations.AlterField(
            model_name='esp8266',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esps', to='userprofile.userprofile'),
        ),
    ]
