# Generated by Django 3.2.4 on 2022-07-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20220710_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esp8266',
            name='mac',
        ),
    ]
